### ISSUE TITLE
PomaOutliers.R

### ISSUE THREAD

**Issue by MPietzke** [pcastellanoescuder/POMA#5]
For the calculation of the limit (in line 76): 

limit <- data.frame(aggregate(detect_outliers$distances, list(detect_outliers$Groups), function(x) {quantile(x, 0.75) + coef * IQR(x)}))

Shouldn't it be "quantile(x, 0.5)"  - the median? 

Also: In my eyes instead of drawing a hull, drawing a circle around the centroid with the distance as radius would allow to see the outlying points more intuitively.

**Comment by pcastellanoescuder** [comment]
Hey @MPietzke!

Not really. According to the classical definition of outliers, atypical values are defined according to formula `Q3 + 1.5 * IQR`, so Q3 (0.75) is used and not the median (0.5). In addition, POMA allows you to modify the classical 1.5 coefficient in order to be more or less restrictive with outliers.

Since POMA calculates outliers based on Euclidean distances, I think a hull is more interpretable than a circle, but of course the double circle/hull option could be added. I will add it to the list of possible improvements and of course, welcome to contribute directly by making a pull request!

Hope it helps!

**Comment by MPietzke** [comment]
Great, thanks for the reply, I just wanted to be sure there isn't a mistake. 
Another question: Does this strategy have a name / a reference that can be checked in more detail or can be cited? 

I still like the idea of the circle, ggforce has a function to draw circles:
https://ggforce.data-imaginist.com/reference/geom_circle.html
You just need to supply the center (centroids) and the radius (limit) - maybe you can use this function. I can add some lines if you want. 

However, I tested this with my own data and it turns out not all the points shown as outlier in the box plots are outside of the circles. 
I guess the reason is that the identification of the outliers (and the representation in the boxplots) is based on all the dimensions, while in the plot only 2 can be shown. So similar to a PCA plot it may be possible that there isn't a strong difference for some samples in PCoA1 vs. PCoA2 but a higher difference in PCoA1 vs. PCoA3. Do you agree? 
This would (unfortunately) complicate the interpretation of the circles in some situations, as someone might be confused if the plot actually doesn't show all the points as outlier that are defined. With my data it's somewhere in the range of Dim1 vs. Dim4 or Dim1 + Dim4 vs. Dim5.

You write: "The method implemented in POMAShiny is based on the distances among observations (euclidean by default) and their distances to each group centroid in a two-dimensional space."
But you don't shrink it down to a 2D space? It's just the representation?

If we take the Poma-Shiny example data (default value for missing value imputation plus autoscaling we can find 5 outlier. The centroids are around 0,0 the limit distance is appr. 20. 

![image](https://user-images.githubusercontent.com/70321724/141092746-4fbbe3bb-15b2-4d7c-8035-7ce906611f47.png)

However in your plot the hull of the CRC samples has a range of ~7.5 in each direction from the center. If we calculate the distance of the the extremes sqrt(7.5 ^2 + 7.5^2) we have the radius of the circle of 10.6, the limit distance is 22, the outlier samples have a distance of 25.  Again this isn't found in the plot.
![image](https://user-images.githubusercontent.com/70321724/141093446-042271f2-121f-49e7-b188-6fe9c2780bf4.png)

Do you think there is actually a way to really shrink it down to 2 dimensions for a true representation? Like PCoA1 vs. PCoA2-n. 

Thanks!

**Comment by pcastellanoescuder** [comment]
Good points right here!

> Great, thanks for the reply, I just wanted to be sure there isn't a mistake. Another question: Does this strategy have a name / a reference that can be checked in more detail or can be cited?

Actually, we developed this ad-hoc method according to our needs in the moment, so you can cite directly the [POMAShiny](https://github.com/pcastellanoescuder/POMAShiny) paper: 

_Castellano-Escuder, P., González-Domínguez, R., Carmona-Pontaque, F., Andrés-Lacueva, C., & Sánchez-Pla, A. (2021). POMAShiny: A user-friendly web-based workflow for metabolomics and proteomics data analysis. PLoS computational biology, 17(7), e1009148._

> I still like the idea of the circle, ggforce has a function to draw circles: https://ggforce.data-imaginist.com/reference/geom_circle.html You just need to supply the center (centroids) and the radius (limit) - maybe you can use this function. I can add some lines if you want.

I still think circles are not a very good idea... Here we are using distances and not probabilities to detect outliers, so using circles would leave some points outside and inside circles without necessarily coinciding with outliers and non-outliers detected according to the method. I think this would be quite confusing for users...

> However, I tested this with my own data and it turns out not all the points shown as outlier in the box plots are outside of the circles. I guess the reason is that the identification of the outliers (and the representation in the boxplots) is based on all the dimensions, while in the plot only 2 can be shown. So similar to a PCA plot it may be possible that there isn't a strong difference for some samples in PCoA1 vs. PCoA2 but a higher difference in PCoA1 vs. PCoA3. Do you agree? This would (unfortunately) complicate the interpretation of the circles in some situations, as someone might be confused if the plot actually doesn't show all the points as outlier that are defined. With my data it's somewhere in the range of Dim1 vs. Dim4 or Dim1 + Dim4 vs. Dim5.

That’s what I’m saying. You have to keep in mind that this algorithm is using a multivariate approach to detect outliers, calculating the multivariate homogeneity of each group variance, and is representing it in a two-dimensional space via a classic MDS plot, so as you say the circles would not work. I want to make it clear that the MDS plot is only for visualization but that the method is multivariate!

> You write: "The method implemented in POMAShiny is based on the distances among observations (euclidean by default) and their distances to each group centroid in a two-dimensional space." But you don't shrink it down to a 2D space? It's just the representation?

You are absolutely right. Thanks for this point. We need to clarify this in the documentation. When we say “in a two-dimensional space” we are only talking about the representation, as you pointed out, the method is multivariate.

> If we take the Poma-Shiny example data (default value for missing value imputation plus autoscaling we can find 5 outlier. The centroids are around 0,0 the limit distance is appr. 20.
> 
> However in your plot the hull of the CRC samples has a range of ~7.5 in each direction from the center. If we calculate the distance of the the extremes sqrt(7.5 ^2 + 7.5^2) we have the radius of the circle of 10.6, the limit distance is 22, the outlier samples have a distance of 25. Again this isn't found in the plot.

Correct and very well pointed out again. The reason is exactly what we discussed above: the method is multivariate and never shrink down the distances to a 2D space but the representation is in 2D.
 
> Do you think there is actually a way to really shrink it down to 2 dimensions for a true representation? Like PCoA1 vs. PCoA2-n.

I really don’t think there is a need to do this as long as the documentation is well explained (I add this "to-do" and thank you again). If you want to have a realistic view of the multivariate distances computed in each group and outliers, I think boxplots can do a good job here. Do you agree?

Thanks!

**Comment by MPietzke** [comment]
Hi Pol, sorry for the late reply! But I think we are on the same page now. 

I completely agree the boxplots are the best representation for the distances. 
And as discussed before, my misunderstanding was that the distances shown in the boxplot should also be found in the PCoA plot - clearly this doesn't need to be the case as there are more dimensions to consider.
